<template>
    <div id="Loader" v-if="isActive">
        <div class="loadingio-spinner-interwind-anq6iy2izap">
            <div class="ldio-opihh3bq8y">
                <div>
                    <div>
                        <div>
                            <div></div>
                        </div>
                    </div>
                    <div>
                        <div>
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script scoped>
export default {
    name: "Loader",
    data() {
        return {
            isActive: this.active || false,
        }
    },
    watch: {
        active(value) {
            this.isActive = value
        },
    }
}
</script>

<style scoped>
@keyframes ldio-opihh3bq8y-r {
    0%, 100% {
        animation-timing-function: cubic-bezier(0.2, 0, 0.8, 0.8)
    }
    50% {
        animation-timing-function: cubic-bezier(0.2, 0.2, 0.8, 1)
    }
    0% {
        transform: rotate(0deg)
    }
    50% {
        transform: rotate(180deg)
    }
    100% {
        transform: rotate(360deg)
    }
}

@keyframes ldio-opihh3bq8y-s {
    0%, 100% {
        animation-timing-function: cubic-bezier(0.2, 0, 0.8, 0.8)
    }
    50% {
        animation-timing-function: cubic-bezier(0.2, 0.2, 0.8, 1)
    }
    0% {
        transform: translate(-45px, -45px) scale(0)
    }
    50% {
        transform: translate(-45px, -45px) scale(1)
    }
    100% {
        transform: translate(-45px, -45px) scale(0)
    }
}

.ldio-opihh3bq8y > div {
    transform: translate(0px, -22.5px)
}

.ldio-opihh3bq8y > div > div {
    animation: ldio-opihh3bq8y-r 1s linear infinite;
    transform-origin: 150px 150px;
}

.ldio-opihh3bq8y > div > div > div {
    position: absolute;
    transform: translate(150px, 123px);
}

.ldio-opihh3bq8y > div > div > div > div {
    width: 90px;
    height: 90px;
    border-radius: 50%;
    background: #049ef4;
    animation: ldio-opihh3bq8y-s 1s linear infinite;
}

.ldio-opihh3bq8y > div > div:last-child {
    animation-delay: -0.5s;
}

.ldio-opihh3bq8y > div > div:last-child > div > div {
    animation-delay: -0.5s;
    background: #222222;
}

.loadingio-spinner-interwind-anq6iy2izap {
    width: 300px;
    height: 300px;
    display: inline-block;
    overflow: hidden;
    background: none;
}

.ldio-opihh3bq8y {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}

.ldio-opihh3bq8y div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>